require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'fundoo_notes' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'ReactNativeLocalization', :path => '../node_modules/react-native-localization'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'

  pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker'

  pod 'RNCPicker', :path => '../node_modules/@react-native-picker/picker'

  target 'fundoo_notesTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'fundoo_notes-tvOS' do
  # Pods for fundoo_notes-tvOS

  target 'fundoo_notes-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
