const Chinies = {
    pass: '密码',
        Forget: '忘记',
        Signup: '注册',
        Login : '登录',
        facebook: '脸书',
        emailId: '熔体',
        firstname: '名字',
        lastname: '姓',
        username: '用户名',
        confirm: '确认',
        signin: '登入',
        next: '下一个',
        Resetpass: '重置通行证',
        welcome: '欢迎',
        responsive: '响应图像',
        error :'发生了错误',
        done: '完成',
        Notes: '笔记',
        Reminder: '提醒',
        newLabel: '创建新标签',
        Archive: '封存',
        Delete: '删除',
        Setting: '设置',
        HelpFeed: '帮助和反馈',
        Logout: 'बाहेर पडणे',
        fundoo: '丰都笔记'
}

export default Chinies;