const English = {
    pass : 'password',
    Forget: 'Forget',
    Signup: 'Signup',
    Login : 'Login',
    facebook: 'Login with facebook',
    emailId: 'email Id',
    firstname: 'First Name',
    lastname: 'Last Name',
    username: 'User Name',
    confirm: 'Confirm',
    signin: 'Sign in instead',
    next: 'Next',
    Resetpass: 'Reset Password',
    welcome: 'Welcome to dashboard',
    responsive:'Responsive Image',
    error : 'error occurred',
    done: 'Done',
    Notes: 'Notes',
    Reminder: 'Reminder',
    newLabel: 'Create new label',
    Archive: 'Archive',
    Delete: 'Delete',
    Setting: 'Setting',
    HelpFeed: 'Help & feedback',
    Logout: 'Logout',
    fundoo: 'Fundoo Notes'
}
export default English