const French = {
    pass: 'mot de passe',
    Forget: 'Oublier',
    Signup: 'S`inscrire',
    Login : 'S`identifier',
    facebook: 'Facebook',
    emailId: 'Melid',
    firstname: 'Prénom',
    lastname: 'nom de famille',
    username: 'Nom d`utilisateur',
    confirm: 'confirmer',
    signin: 'se connecter',
    next: 'prochain',
    Resetpass: 'Réinitialiser le mot de passe',
    welcome: 'Bienvenue',
    responsive: 'image réactive',
    error:'Erreur',
    done: 'terminé',
    Notes: 'Remarques',
    Reminder: 'Rappel',
    newLabel: 'créer une nouvelle étiquette',
    Archive: 'Archiver',
    Delete: 'Effacer',
    Setting: 'Réglage',
    HelpFeed: 'Aide et commentaires',
    Logout: 'Se déconnecter',
    fundoo: 'Notes de Fundoo'
}

export default French;