const hindi = {
        pass: 'कुंजिका',
        Forget: 'भूल',
        Signup: 'साइन अप करें',
        Login: 'लॉग इन करें',
        facebook: 'फेसबुक में जाये',
        emailId: 'ईमेल आईडी',
        firstname: 'पहला नाम',
        lastname: 'उपनाम',
        username: 'उपयोगकर्ता नाम',
        confirm: 'पुष्टि करें',
        signin: 'साइन इन करें',
        next: 'आगे',
        Resetpass: 'पासवर्ड रीसेट',
        welcome: 'डैशबोर्ड पर आपका स्वागत है',
        responsive: 'उत्तरदायी छवि',
        error: 'त्रुटि हुई',
        done: 'किया हुआ',
        Notes : 'टिप्पणियाँ',
        Reminder: 'अनुस्मारक',
        newLabel: 'नया लेबल बनाएं',
        Archive: 'पुरालेख',
        Delete: 'हटाएं',
        Setting: 'स्थापना',
        HelpFeed: 'सहायता और प्रतिक्रिया',
        Logout:'लॉग आउट',
        fundoo: 'फंडू नोट्स'
}

export default hindi;