const Marathi = {
    pass: 'संकेतशब्द',
    Forget: 'विसरा',
    Signup: 'साइन अप',
    Login : 'लॉगिन',
    facebook: 'फेसबुक सह लॉगिन करा',
    emailId: 'ई - मेल आयडी',
    firstname: 'पहिले नाव',
    lastname: 'आडनाव',
    username: 'वापरकर्तानाव',
    confirm: 'पुष्टी',
    signin: 'साइन इन',
    next: 'पुढे',
    Resetpass: 'संकेतशब्द रीसेट करा',
    welcome: 'डॅशबोर्डवर आपले स्वागत आहे',
    responsive: 'उत्तरदायी प्रतिमा',
    error:'त्रुटी आली',
    done: 'केले',
    Notes: 'टीप',
    Reminder: 'स्मरणपत्र',
    newLabel: 'नवीन लेबल तयार करा',
    Archive: 'संग्रह',
    Delete: 'हटवा',
    Setting: 'सेटिंग',
    HelpFeed: 'मदत आणि अभिप्राय',
    Logout: 'बाहेर पडणे',
    fundoo: 'फंडू नोट्स'
}
export default Marathi;